version: "3.7"
services:
  app:
    build: .
    container_name: app
    ports:
    - 8080:8080
    depends_on:
      - db
    environment:
      profile: prod
      db_pass: 12345678
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: BankServer
      MYSQL_USER: bankUser
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: "dlink"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql