version: "3.7"
services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      profile: prod
      db_pass: 12345678
    network_mode: host
  db:
    image: mysql:8.0.23
    container_name: db
    environment:
      MYSQL_DATABASE: BankServer
      MYSQL_USER: bankUser
      MYSQL_PASSWORD: 12345678
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql