basePath: /
definitions:
  swagger.UserLogin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  swagger.UserSignUp:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for test task.
  title: API-Server
  version: "1.0"
paths:
  /login/:
    post:
      consumes:
      - application/json
      description: user login
      operationId: user-login
      parameters:
      - description: username and password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/swagger.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      summary: Login
      tags:
      - Authorization
  /logout/:
    get:
      consumes:
      - application/json
      description: user logout
      operationId: user-logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - Authorization
  /payment/:
    get:
      consumes:
      - application/json
      description: balance payment
      operationId: balance-payment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      security:
      - ApiKeyAuth: []
      summary: payment
      tags:
      - Payment
  /refresh-token/:
    get:
      consumes:
      - application/json
      description: refresh token
      operationId: ref-token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      security:
      - ApiKeyAuth: []
      summary: RefreshToken
      tags:
      - Inner_Handlers
  /signup/:
    post:
      consumes:
      - application/json
      description: create user
      operationId: create-user
      parameters:
      - description: signup user
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/swagger.UserSignUp'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      security:
      - ApiKeyAuth: []
      summary: Signup
      tags:
      - Inner_Handlers
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
